sqrtbabyex:
	cobc -x -free -W -d sqrtbabyex.cob
	cobc -m -free -W -d squareroot.cob
	./sqrtbabyex
	make clean

sqrtbaby:
	cobc -x -free -W -d sqrtbaby.cob
	./sqrtbaby
	make clean

clean:
	rm -rf sqrtbabyex squareroot.so sqrtbaby
