GFLAGSX = -Wall -Wextra -pedantic -fimplicit-none -fbacktrace -Wsurprising -fcheck=mem -fcheck=do -fcheck=all

GFLAGS = -Wall -Wextra -pedantic -fimplicit-none -fbacktrace -Wsurprising -fcheck=mem -cpp

TASK1 = luc.f95

TASK2 = hex.f95 luchex.f95

main:
	gfortran $(GFLAGSX) $(TASK2)
	./a.out
